name: CI

on:
  push:
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'
  pull_request:
    branches: master
    paths-ignore:
      - '.appveyor.yml'
      - NEWS
      - 'xapian-maintainer-tools/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  macos:
    runs-on: 'macos-latest'
    env:
      LIBEXTRACTOR_PREFIX: '/usr/lib/x86_64-linux-gnu/libextractor'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: macos
    - name: Install package dependencies
      run: |
        brew update
        # libabw seems to have gone?
        # Workaround collision from mono package to something else.
        # mono seems to collide with a different version of mono?
        # tesseract worker fails to build: /usr/local/Cellar/tesseract/5.0.1/include/tesseract/baseapi.h:21:12: fatal error: 'config_auto.h' file not found
        brew install \
            doxygen \
            gmime \
            graphviz \
            help2man \
            icu4c \
            libarchive \
            libcdr \
            libetonyek \
            libextractor \
            libiconv \
            libmagic \
            libmwaw \
            libsvm \
            lua \
            pcre2 \
            pkgconfig \
            pngcrush \
            poppler \
            python
        pip3 install sphinx docutils
        mkdir -p '${{ runner.temp }}/xapian-libsvm-fixed-include'
        ln -sF "`ls -1d /usr/local/Cellar/libsvm/3.*/include|tail -n 1`" '${{ runner.temp }}/xapian-libsvm-fixed-include/libsvm'
    - name: bootstrap source tree
      run: ./bootstrap xapian-core xapian-applications/omega
    - name: configure
      run: ./configure CC='ccache gcc' CXX='ccache g++' CPPFLAGS='-I${{ runner.temp }}/xapian-libsvm-fixed-include' PYTHON3=/usr/local/bin/python PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig --prefix='${{ runner.temp }}/XapianInstall' --with-libiconv-prefix=/usr/local/opt/libiconv
    - name: make
      run: |
        make -j3
        make -C xapian-core install
    - name: Run tests
      run: make -j2 -C xapian-applications/omega check VERBOSE=1 AUTOMATED_TESTING=1
    - name: Check generated files are in .gitignore
      # grep '^' passes through all input while giving a non-zero exit status
      # if that input is empty.
      run: |
        find . \( -name 'config.guess~' -o -name 'config.sub~' -o -name 'install-sh~' \) -delete
        git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
